package kg.easyit.onlineshop.model.enums;

public enum Authority {
    USER_READ,
    USER_CREATE,
    USER_DELETE,
    USER_UPDATE,

    ACCOUNT_CREATE,
    ACCOUNT_READ,
    ACCOUNT_DELETE,
    ACCOUNT_UPDATE,

    BASKET_CREATE,
    BASKET_READ,
    BASKET_DELETE,
    BASKET_UPDATE,

    ORDER_CREATE,
    ORDER_READ,
    ORDER_DELETE,
    ORDER_UPDATE,

    PRODUCT_CREATE,
    PRODUCT_READ,
    PRODUCT_DELETE,
    PRODUCT_UPDATE,

    TRANSACTION_CREATE,
    TRANSACTION_READ,
    TRANSACTION_DELETE,
    TRANSACTION_UPDATE,

    PERMISSIONS_READ,
    AUTHORITY_READ

}
